### PR TITLE
Adding checks on some Lambda fields

### PR DESCRIPTION
**Pull request by cmorell**
Due a missing good configuration in Lambda, There are a problem in b118877 commit version. This missing configuration causes the following error:
'role': self.role.arn.full, AttributeError: 'NoneType' object has no attribute 'arn'

To avoid it, I've changed the creation of the Lambda Object in core/Lambda.py and also how Scan.py is reading this object and how /visibility/Statistics.py and /visibility/HTMLReport.py is creating the report.

Maybe is not the best solution, but for me, works (with a aws account working in b118877 commit version and with the aws account that cause my error.

### CODE REVIEW

**Comment by adeptex** [comment]
hey @cmorell thanks for submitting a PR! It appears that CI build did not succeed with your changes: https://travis-ci.org/Skyscanner/LambdaGuard/builds/640136933 

It is essential that your code passes lint and unit tests before we can merge it!

**Comment by cmorell** [comment]
Yes, I saw it.
I'll do it and i'll push it again.

Thanks!

**Comment by cmorell** [comment]
Hi,

I've seen there are conflicts because you did a change in Lambda.py 
As far as I can check, you've changed get_function function. 

In this file, I've only changed report function. Then, I don't know how can we proceed. If you want to delete de pull request and I'll do it again, or you resolve conflicts on this PR.

**Comment by adeptex** [comment]
I think the easiest way at this point would be to clone from master and reapply the changes locally.

**Comment by adeptex** [comment]
Hey @cmorell have you tried the new LambaGuard version? Does the error still happen for you there? Can we close this PR or are you planning to resolve conflicts?

**Comment by adeptex** [comment]
Closing this as abandoned

**Pull request closed without merging**
